Homework_7 to check
IsaevMH/MaximIsaev pull request #7
Opened 2021-08-26 20:07 UTC by IsaevMH

2021-09-01 18:16 UTC, pnatashap requested changes
A lot changes are required. Comments are in code

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/entity/Data.java
> +//    @Override
It's a bad practice to store commented code. If it's not used - should be removed

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/IndexPage.java
> +    public static WebElement userIcon;
Elements from native selenium should not be used.  in JDI there is an Icon for this type

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/IndexPage.java
> +    public static WebElement metalsColorsMenuOption;
There is a type Link, for example

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/MetalsColorsFormPage.java
> +
Why this page is empty?

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/DataProviderJson.java
> +    @DataProvider(name = "test-data")
Also a very common name, but in case of test it should be unique for all

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/TestInit.java
> +        openSite(SiteJdi.class);
open is a part of init

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/metalsColorsPageTest.java
> +        indexPage.login.setValue(DataReader.getProperty("login"));
1. Login is a precondition for the test.
2. Login should be implemented as login via Form<User>.

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/metalsColorsPageTest.java
> +        List<String> expectedResult = ExpectedResultCreator.getExpectedResultList(data);
For now the first test is failed on assert, but all others are failed due to failed login. It's a very bad situation: test should failure on correct place, for parametrized test it's very important

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/metalsColorsPageTest.java
> +public class metalsColorsPageTest implements TestInit {
Java name convention: Class name should start from TitleLetter

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/testng/TestNGListener.java
> +    public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
What is the reason for this class?

2021-09-01 18:16 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/utils/StringCreator.java
> +public class StringCreator {
Usually all classes in util are also have a postfix Util in name for visibility.

2021-09-01 18:22 UTC, IsaevMH commented on src/test/java/com/epam/tc/hw7/driver/Driver.java
> +public class Driver {
Sorry, I copied all packages from the previous homework...
The issue is fixed.

2021-09-01 18:27 UTC, IsaevMH commented on src/test/java/com/epam/tc/hw7/entity/Data.java
> +public class Data extends DataClass<Data> {
The issue is fixed

2021-09-10 20:28 UTC, pnatashap requested changes
Comments are in a code

2021-09-10 20:28 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/entity/LoginFormData.java
> +        fullName = "ROMAN IOVLEV";
Very strange logic: login and password from dataREader, but full name is hardcoded. 
All data should have one source: you should change the data in ONE place

2021-09-10 20:28 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/page/IndexPage.java
> +    @UI("//ul/li/a[text() = 'Metals & Colors']")
The full path is not stable for site changes, so it's better to change locator to simple link with text.

2021-09-10 20:28 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/section/LoginForm.java
> +        userIcon.click();
userIcon is not a part of the form, we cann't click on it from this place.

2021-09-10 20:28 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/service/DataReader.java
> +public class DataReader {
The name of the class is very common, it's better to change it to more specific

2021-09-10 20:28 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/DataProviderJson.java
> +            resultArray[++i][0] = dataEntry.getValue();
Very sophisticated logic with start from -1 and ++i. It's better to keep code easy understandable

2021-09-10 20:28 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/MetalsColorsPageTest.java
> +        List<String> expectedResult = ExpectedResultCreatorUtil.getExpectedResultList(metalsColorsFormData);
Test is failed if executed without the first test. All tests should be isolated and do not influence to each other.

2021-09-10 20:28 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/TestInit.java
> +        openSite(SiteJdi.class);
comment is not fixed

2021-09-27 16:35 UTC, pnatashap requested changes

2021-09-27 16:35 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/section/LoginForm.java
> +        signInButton.click();
submit is not a part of fill. There is a separate method for submit

2021-09-27 16:35 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/TestInit.java
> +        openSite(SiteJdi.class);
still not fixed and there is no any answer

2021-09-27 16:35 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/TestInit.java
> +        logout();
Why do we need logout?

2021-09-27 16:35 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/MetalsColorsPageTest.java
> +                .isNotEqualTo(expectedResult);
Expected result - the data should match

2021-09-27 16:35 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7/test/TestInit.java
> +        login();
Your implementation of login is not guaranteed that we are logged in. So it should be checked

2021-09-29 09:36 UTC, pnatashap approved these changes

2021-09-29 12:00 UTC, merged